version: "3" # composeファイルのバージョン
services: 
    goapp: # サービス名
        build: . # ①ビルドに使うDockerfileの場所
        tty: true # ②コンテナの永続化
        volumes:
            - .:/go/src # ③マウントディレクトリ
        ports: 
            - "80:8080"